### ISSUE TITLE
Symbol popup under my finger

### ISSUE THREAD

**Issue by McIrco95** [futo-org/android-keyboard#1]
When holding a key to get a special character the popup is not one line above but right under my finger. And when i move my finger of the popup it starts swiping. 
![Screenshot_20240508-161401](https://github.com/futo-org/android-keyboard/assets/115875304/166c2397-4abe-4fdd-8aa0-63d395a80232)

**Comment by abb128** [comment]
Fix will be deployed in the next update

**Comment by abb128** [comment]
@brckd Can you include a screenshot and description of your issue? It might be a different issue

**Comment by brckd** [comment]
Sure, here is a row of screenshots that show what happens when I try to use the upper row of long press symbols.

![Screenshot_20250212-081741.png](https://github.com/user-attachments/assets/6d51d133-f8dd-490f-b994-460145673ebf)

![Screenshot_20250212-081754.png](https://github.com/user-attachments/assets/a48945d3-057d-4f79-8cb1-41b2c29532b5)

![Screenshot_20250212-081802.png](https://github.com/user-attachments/assets/285b763a-78a3-47ef-8c32-d81ffd2a3b13)

**Comment by brckd** [comment]
OK, sorry for the confusion then.
