### ISSUE TITLE
Georgian Keyboard Zhani character issue

### ISSUE THREAD

**Issue by abb128** [futo-org/android-keyboard#113]
![image](https://github.com/futo-org/android-keyboard/assets/65567823/1a66b621-9581-46b3-90b6-d00b34a253d8)

**Comment by Fibodachi** [comment]
I would like to add additional context for this bug. The main script used for communication in Georgian (Mkhedruli) has no letter case, that is, there are no upper/lowercase letters. There are capital-like letters that constitute another script and have very narrow and specific uses, but they are not used in everyday communication. Georgian alphabet has 33 letters, but the prevalent keyboard layout is modeled on QWERTY, which means that not all letters fit in the standard layout. Shift key is used to access the letters that do not fit, for example, pressing "T" would type "ტ" without shift and "თ" with shift. There was an issue that cropped up a few years ago in AOSP keyboard where pressing shift would not only show the rest of the letters, but also needlessly capitalize them i.e what should have been თ came out as Თ. The expected behavior is that pressing shift should give access to the rest of the letters without capitalizing them. The letters in question are ჭ, ღ, თ, ჟ, შ, ძ, ჩ

**Comment by skysphr** [comment]
I believe deleting the Georgian character pairs from LatinCapitalSmallPair in native/jni/src/utils/char_utils.cpp would fix this issue.

**Comment by svalbardsleeperdistrict** [comment]
This problem is the only issue preventing me from using the keyboard, which is a shame because otherwise it's just great and I would like to use it to replace MS SwiftKey. Every time I want to use the Shift+key version for წ/ჭ, რ/ღ, ტ/თ, ს/შ, ჯ/ჟ, ზ/ძ and ც/ჩ, it has to be a capitalised version of the latter, and it makes the resulting words look very janky. Would be so nice if this could be fixed.

**Comment by abb128** [comment]
This is fixed in nightly, please test it if you can and let me know if the Georgian keyboard is correct now @svalbardsleeperdistrict 
https://keyboard.futo.org/nightly.apk

**Comment by svalbardsleeperdistrict** [comment]
> This is fixed in nightly, please test it if you can and let me know if the Georgian keyboard is correct now @svalbardsleeperdistrict https://keyboard.futo.org/nightly.apk

It's perfect, thank you.
