### ISSUE TITLE
Payment Unsupported on Play Store

### ISSUE THREAD

**Issue by esperl** [futo-org/android-keyboard#121]
Version Name: 0.1.22-playstore
Version code: 10804

I am unable to pay for the Software. When i press the "Pay" button under Payment in the "FUTO Keyboard" app an error toast appears stating that 

"Payment is unsupported on this build"
![Screenshot_2024-07-02-11-14-07-329_org futo inputmethod latin playstore](https://github.com/futo-org/android-keyboard/assets/62929699/21769c5f-2b21-4537-946c-5c0e3fa3fe5f)

**Comment by singatias** [comment]
Same thing here, using stock android with fairphone 4

**Comment by abb128** [comment]
Please pay using the pay button on the website: https://keyboard.futo.org/
![Screenshot_20240702_203355](https://github.com/futo-org/android-keyboard/assets/65567823/7dd1912a-0166-4647-9744-63706e90f505)

We can't support Play Store in-app purchases at this time due to their payment SDK requiring the app to have internet permission

**Comment by abb128** [comment]
This was fixed in v0.1.23 with a separate payment app
