### ISSUE TITLE
Swipe Typing Fails to Follow Fast Typing

### ISSUE THREAD

**Issue by maamursu** [futo-org/android-keyboard#131]
I have been using swype typing for a decade, and know the qwerty layout by heart. On MS swift key I can dance through the letters of a word very fast, with a few tricks to emphasize the letters to the algo.
Those being 
making arcs from letter to another instead of a straight line when letters line up
Making a tiny loop above wanted character
Short pause over wanted character.
Sadly I feel like making a pause is the only reliable way here, but it is the slowest option and at times I feel like tap typing might he just as fast especially with short words.
A good example of my issue is typing "our" fast - all 3 letters are on the same row, and without actually stopping over "u" I usually don't even get "our" in the suggestions unless it is very obvious by context.
So I hope that the algo could be trained to recognise these cues Better..?

**Comment by QuickNET-Tech** [comment]
Swipe typing in general seems pretty poor:
- I can't get it to type hehe, lol, lmao, idk, ikr, tbh and ass as some examples
- It sometimes just gives up and types nothing and doesn't give suggestions either
- It doesn't seem to learn in any way
- It seems to favor acronyms over words in many cases e.g. "UK" > "I'll", "PT" > "pot"
- Generally just feels jank (can't get it to type the word jank lol) and cumbersome as I'm having to take multiple attempts at a lot of the words I swipe and I often just give up and tap type because swipe simply won't work

**Comment by iamshamit** [comment]
it doesnt support hinglish too (it should remeber the words that has been typed often and it should make it its context while swipe typeing) 

(just a suggestion)

**Comment by kjkrum** [comment]
I've also noticed swipe seeming to favor acronyms, proper names, and obscure words. For example, I constantly get "Anna" when I try to swipe "and". But my programmer's instinct is that it's not actually favoring these weird words. The "best match" algorithm is probably giving zero weight to how common the possible matches are in the current language or document, and giving you the dictionary word that is strictly the best match for the input regardless of how strange of a word it is.

**Comment by maamursu** [comment]
this is why I usually blacklist some of the weird town names and such that
come in place of common words. After a few months you ge trid of the
annoying ones, haha

**Comment by dean-futo** [comment]
Consolidated into #665
