### ISSUE TITLE
Import file selector immediately crashes

### ISSUE THREAD

**Issue by bradn2** [futo-org/android-keyboard#182]
I don't know if this is an easy thing to get around but the file selector immediately crashes on my phone (Android 11 3rd party ROM) but this is not an uncommon kind of problem in Android in general.

It would be nice to have an import option that lets me enter a unix path directly.  I can inject the voice files into the files folder in the app and then import them that way.  For normal people you could include an optional permission to allow file access so that this option can be usable without using root or a recovery to insert the files to an accessible location.

As an extra data point, I've installed OI File Manager which provides an intent handler that works with apps like FTPClient and lets me select files for that app.  Perhaps investigating how FTPClient - https://codeberg.org/qwerty287/ftpclient - invokes the file selector and adding this as a second option (maybe a checkbox like "Use alternate file chooser method") or similar could help situations like mine.

**Comment by abb128** [comment]
One other user reported this issue and it turned out to be because in the process of debloating they had disabled all files access for External Storage or Download Manager:
1. Go into settings on your phone and search for "All files access"
2. Open it and tap the 3-dot menu in the top-right corner, and tap "Show System"
3. Find "External Storage" and "Download Manager" and make sure "Allow access to manage all files" is enabled for both

Unix path would require the app to have full filesystem access, which is an extremely unnecessary permission for a keyboard and not something that will be added

**Comment by bradn2** [comment]
I wish it were that simple - I'm running a 3rd party ROM where this is a known problem.  When I first go into those apps in settings, permissions is greyed out for both of those apps.  If I go into "open by default" and back, I can then click into permissions, and "Files and media" is enabled for both.  Nothing changes with the behavior.

I understand entering a unix path isn't a fix for the normal person (and I agree, file access permission should not be added), but it is for me because I can use a custom recovery to insert the file into the app's "files" folder and could then tell it to install from a file already inside the app which it does have access to.  Or if there's just a certain naming I have to give the file in there for it to load, I could do that.  I can't figure out what the app does when it "installs" the file though.

A better fix is an option to invoke the file selector the way FTPClient does, because that way does work for whatever reason, if that way doesn't require extra permissions.

Alternately, there's only 3 total language models, could just make 3 apk's for sideload.

**Comment by abb128** [comment]
The intent that's invoked is a standard intent that's existed since Android 4.4 KitKat and if something like that is known to be missing on your ROM you may want to consider switching to something better supported. I will not be adding unnecessary permissions or maintaining 3x the number of APKs just to mitigate a problem with one broken ROM, although you could build your own APK if you want as the source code is right there.

Have you tried opening the .dict or .bin file itself from an app like Firefox, DuckDuckGo or Material Files? FUTO Keyboard registers itself as an option to open binary files as an alternative to the import file selector.

**Comment by bradn2** [comment]
Problem solved - I had no idea it registered as a handler for .bin files - that method works!!
