### ISSUE TITLE
Bulgarian Phonetic kayboard Layout.

### ISSUE THREAD

**Issue by VasilKotsov** [futo-org/android-keyboard#263]
Please add the Bulgarian Phonetic and Phonetic Traditional  Keyboard Leyouts.

**Comment by onestan** [comment]
Thank you for opening this issue! I came here to say that the only thing stopping me from fully switching to the FUTO keyboard is the absence of Bulgarian Traditional Phonetic layout.

**Comment by MiCRoPhoBIC** [comment]
This is a huge deal breaker for Bulgarian users - the only available layout in the app is Bulgarian BDS (and this is the oldest "boomer" standard, since typewriter era and only 50-60+ years old are using it). 
Probably 80-90% of Bulgaria's populations is using the most popular "Bulgarian Phonetic Traditional" layout.
Please add the Bulgarian Phonetic and Phonetic Traditional Keyboard Layouts.
I already bought the app 🥲

**Comment by abb128** [comment]
Duplicate of #63
