### ISSUE TITLE
Backspace Sometimes Unresponsive

### ISSUE THREAD

**Issue by ejerke** [futo-org/android-keyboard#282]
Filing this issue I'm currently having a hard time reproducing this issue. But sometimes when I need to delete some text the keyboard just straight up doesn't delete any characters, the cursor blinks the same way as if it was deleting stuff but nothing happens. After spamming or holding down backspace, it starts to work after a while.

**Comment by ejerke** [comment]
I was able to capture the bug with screen record! Happened in chrome app, everything updated to the latest versions.
Android 14, OneUI 6.1.

https://github.com/user-attachments/assets/17a1a9ca-f6af-4523-a249-0cb26f87cd8f

**Comment by srikary12** [comment]
This issue can be replicated using emojis. While using emojis backspace doesn't work.

**Comment by tellengold** [comment]
Only happens to me inside of the Notion app so far, but it happens consistently.

**Comment by dean-futo** [comment]
Consolidated into #673

**Comment by dean-futo** [comment]
#564 is a duplicate - merging that issue into this one. Both have to do with the backspace key acting erratically and sometimes having to be pressed multiple times to become responsive.

**Comment by frodri** [comment]
I can confirm that this issue is also reproducible when using the "Bluetooth Keyboard and Mouse" app on Google's Play Store: https://play.google.com/store/apps/details?id=io.appground.blek&hl=en-US

I've tested this on both my Pixel 5a and my Pixel 8a, and both of them are showing issues with the backspace key when transmitting the backspace key from the keyboard to the app.

**Comment by abb128** [comment]
I have not tested with the Bluetooth app but this should hopefully be improved in the next update
