### ISSUE TITLE
[Feature request] Change the default letter when long press depending on language

### ISSUE THREAD

**Issue by xEska1337** [futo-org/android-keyboard#288]
Add option or make it a default, when you change language, special characters for this language should be first when long presed like on the samsung keyboard 

Futo keyboard
![Screenshot_20240704_143333_Iceraven.png](https://github.com/user-attachments/assets/3648f8d6-4af9-4cec-a88c-7703360ddcc0)

Samsung keyboard 
![Screenshot_20240704_143345_Iceraven.png](https://github.com/user-attachments/assets/09fc3a8a-05f9-47a2-bd5a-77c2d2c50c04)

**Comment by igoro00** [comment]
I was just about to create the same issue. This makes this keyboard very hard to use (at least for Polish language). `Ł` being at the end of `L` menu is sooo frustrating.

Another thing: in Polish we have two special characters based on `z`: `ż` and `ź`. In all mobile keyboards(except FUTO) `ż` is the default special character for `z` and `ź` is just one to the **right** of `ż`. Here, for some reason when you long press `z` you get `*` in the center, `ż` to the right and `ź` to the left (and there's `ž` which is from a completely different language but ok). `ź` is never to the left of `ż`! Not in any mobile keyboard, not on any computer keyboard (where `AltGr+Z=Ż` and `AltGr+X=Ź`)! 

What I'm trying to say is that you can't just force a default character in the menu for a given language. You need to be able to set the menu layout for every character in every language separately. I don't know how your layout code works so this might be really easy to fix or really difficult but either way it needs to be fixed because those "quirks" exist for nearly every language on earth.

**Comment by abb128** [comment]
You will be able to configure which one is default in the next version:
![image](https://github.com/user-attachments/assets/d978d9c7-15a5-4b13-a854-b0687eb3d61e)
