### ISSUE TITLE
No separate language toggle button.

### ISSUE THREAD

**Issue by Martenfur** [futo-org/android-keyboard#319]
Hello. I would like to see an option to swap out the emoji button for a language toggle button and disable language toggle by holding spacebar. Current language toggle method via holding spacebar is very clunky.

Example of this feature:

![image](https://github.com/user-attachments/assets/306dc5b6-222c-4a5f-a019-9d207bc28247)

**Comment by ioandal** [comment]
Please, do this. I can't use the keyboard since I am constantly changing languages while I am typing and having to hold spacebar to swap is really slow and clunky. 
Thank you.

**Comment by Martenfur** [comment]
> Please, do this. I can't use the keyboard since I am constantly changing languages while I am typing and having to hold spacebar to swap is really slow and clunky. Thank you.

Same, this keyboard has everything I want out of it but this not having this feature is a dealbreaker.

**Comment by juanabia90** [comment]
Same here, this would be a massive improvement. And if I may add to this, I'd love this button to instantly cycle between languages instead of opening a window to make your selection. This should especially be the case when only 2 languages are active. Aside from implementing both languages at once like Gboard does, this would be the best option IMO.

**Comment by abb128** [comment]
This is now fixed after 0.1.23. To customize the button, click the 3 dots on the keyboard and click Edit Actions, or go to Settings > Keyboard & Typing > Edit Actions. You can drag a different action, such as the language switch key, into the Action Key slot.
