### ISSUE TITLE
[Feature request] favorite utility

### ISSUE THREAD

**Issue by FireNinja7365** [futo-org/android-keyboard#33]
Add a drop down menu in the settings to select what function will appear in the top right corner of the keyboard (the default being voice to text)
![Screenshot_20240618-195448-950](https://github.com/futo-org/android-keyboard/assets/157768191/f51ee7c4-c0fc-4636-88ad-a34d341b3796)

**Comment by Progaros** [comment]
Additional Idea: Add the microphone to the menu under the arrow:
![image](https://github.com/futo-org/android-keyboard/assets/22076711/939da711-c73d-483b-bb80-cd56e8061b6c)

then show or hide as many (including e.g. the mic or another utility) as you want
![image](https://github.com/futo-org/android-keyboard/assets/22076711/06284884-e89d-4f5b-bb89-209cf2e970b8)
the arrow button would become e.g. some sort of "eye" button to filter the hidden elements

**Comment by Doc-4** [comment]
I'd really like a feature like this, more so I'd like a feature that lets you have more than one of them pinned at once. My layout on heliboard has 4 functions (technically 7 since the first 3 have alternate functions on hold instead of tap) one press away, and I'd love to have something like that here
![Screenshot_20240626-185455](https://github.com/futo-org/android-keyboard/assets/60247583/1912c1d1-211a-4237-908f-00b7c91409e8)

**Comment by abb128** [comment]
This will be included in the next release
