### ISSUE TITLE
Not supported keyboard

### ISSUE THREAD

**Issue by DragonHeart69** [futo-org/android-keyboard#334]
My bankapp closed and open a webpage, not supported keyboard. App is installed from de playstore.![Screenshot_20240722-210814.png](https://github.com/user-attachments/assets/0a07de16-ef89-4ea6-ae5e-7601f387905b)

**Comment by MulverineX** [comment]
Banking app stupidity continues, yeah there's probably not a good path forward right now for this to be resolved until/if this app becomes more popular

**Comment by abb128** [comment]
Unfortunately there's nothing we can really do on the application side to fix this. You can try complaining to your bank to stop blocking FUTO Keyboard, and using the bank's website instead of the app until they fix this. If there's some technical requirement they demand from keyboards to be not be blocked, you can open a new issue or direct them to open an issue here.
