### ISSUE TITLE
Customize special characters while holding keys

### ISSUE THREAD

**Issue by joaovgp** [futo-org/android-keyboard#349]
Is there any way to customize the special characters that show up when you hold the key for a while?
This is mostly an issue for languages other than english that have a lot of special characters like ç, á, ã (and other vowel variations). I have become accustomed to the GBoard layout of special characters and it would be very nice if I could customize the placement of those special keys.

**Comment by AggressiveHayBale** [comment]
I concur or at least make the language specific symbols the first option under the long press. The issue occurs for me on the polish keyboard.

**Comment by abb128** [comment]
In v0.1.23.2 the default has been made to show language specific letters, and the other symbols/letters can be customized in the long-press key settings, e.g. you can disable miscellaneous letters from other languages as @kaesekarl mentioned
![image](https://github.com/user-attachments/assets/92b330cf-2acd-4696-a0a5-21004629ba4d)

You can't customize individual letters though. If you want any specific adjustments for some language that isn't addressed by the layout option above, please make an issue for those, but make sure to update to 0.1.23.2 before doing so because it may have already changed some things.
