### ISSUE TITLE
Keyboard doesn't work for my Banking app

### ISSUE THREAD

**Issue by BatDevil** [futo-org/android-keyboard#417]
### What happened?

when i downloaded Futo Keyboard, my Banking app keeps directing me to the website, a common problem for Banking apps with Third party keyboards.

### Keyboard Version

0.1.23.2

**Comment by abb128** [comment]
Unfortunately there's nothing we can really do on the application side to fix this. You can try complaining to your bank to stop blocking FUTO Keyboard, and using the bank's website instead of the app until they fix this. If there's some technical requirement they demand from keyboards to be not be blocked, you can open a new issue or direct them to open an issue here.
