### ISSUE TITLE
Add Option to Change Word Capitalization After Typing

### ISSUE THREAD

**Issue by Mamacanoa** [futo-org/android-keyboard#449]
### Use Cases

To change the capitalization of a word after it has been typed, I have to tediously jump back between the first and second letter, delete the first letter and type the capital letter. If I want all caps, I need to delete the whole word and type it again.

### Proposal

After I type a word, with the cursor still in the position right behind the word, click once to change the first letter of the word, tap twice to change the letters to all caps

**Comment by BoscoDomingo** [comment]
Click where, exactly?

**Comment by Mamacanoa** [comment]
Sorry, on the Shift key of course

**Comment by rhubear25** [comment]
> Sorry, on the Shift key of course

Correct, I found this out by accident.

I also wanted this feature.  Then I found that by highlighting word to edit, then clicking SHIFT key (mult times), the highlighted word cycles through "initial cap", "all caps", "all small".... Perfect for my use.   

Thanks FUTO....

PS:  when I use voice to text, I input small phrases at a time, not full sentences.  At each start of "voice capture", text is inputted using initial CAP, which is why I have unwanted random words w an Initial Cap, so the SHIFT key Cap Changes really help me to edit my final text.

**Comment by mtsarge** [comment]
OK! Being able to capitalize by selecting the word is helpful, but I do still wish it worked similarly to how OP suggested, by moving the cursor to the end of the word you want to change. This is how Swiftkey works and I miss it.

**Comment by dean-futo** [comment]
@Mamacanoa thanks for your suggestion but we're going to continue using our current method for changing case because it's more reliable and helps avoid accidental changes.

**Comment by jksekai** [comment]
almost only thing missing keeping this keyboard from a perfect Swiftkey alternative to futo
