### ISSUE TITLE
Swipe Typing very Inaccurate

### ISSUE THREAD

**Issue by 4Bakers** [futo-org/android-keyboard#530]
### What happened?

Samsung Galaxy S9+
Android 10 / OneUI 2.5
Any text input

1. use swipe typing (demonstration message below, errors in strike-through)

I've ~~find~~ found that the ~~store spur store spur swore~~ swipe typing is very difficult to use, and ~~Ogden own~~ often ~~SOS spa spots spots spots spots spots spa~~ spits ~~it~~ out a wide variety of incorrect ~~outposts outposts~~ outputs, ~~carrying~~ varying from reasonable mistakes to downright ~~baking basking being belong~~ baffling results, some even being words ~~ice~~ I've never ~~hard~~ heard of before.
I love the privacy of FUTO keyboard, but I ~~one no~~ don't ~~Rico TCP~~ think ~~is is is~~ it's worth losing my ~~store~~ swipe typing just to have ~~IR~~ it.

### Keyboard Version

0.1.23.2-playstore

### Text field info

due to the nature of the issue, this occurs in any text field

**Comment by neuron303** [comment]
That's probably the reason why the feature is called alpha in the settings.
But it seems it is enabled by default so not everybody sees that.

I would expect improvements here based on its alpha state.

**Comment by 4Bakers** [comment]
> That's probably the reason why the feature is called alpha in the settings.
I'm sure that's why lol
thanks for pointing that out! 
here's to hoping it improves in the future.

**Comment by zaquarius** [comment]
I think a big part of the issue (same with the suggestion bar) is that it seems to treat uncommon words as equally likely as more common words. It's like it's using scrabble rules, where anything that is technically a word is equally valid, rather than assumimg "issue" is probably more likely than "USO" just as an example that happened while typing this, and similar random letters happen all the time

**Comment by 4Bakers** [comment]
@zaquarius
big agree lol
I noticed that a lot

**Comment by dean-futo** [comment]
Consolidated into #665
