### ISSUE TITLE
Add Shift Key Functionality for Post-Typing Capitalization

### ISSUE THREAD

**Issue by Annihilaton** [futo-org/android-keyboard#557]
### Use Cases

- Cannot capitalize words after typing
- No added space after selecting a suggestion

### Proposal

- after typing a word, if you press shift, the suggestion should capitalize the first letter
- after selecting a suggestion, a space should be added, because it will add one anyway, when you start typing again. But if you want to delete the space you need to first start typing again which is pretty annoying imo

**Comment by dean-futo** [comment]
@Annihilaton thanks for your request, but this could become messy because we already have a method for capitalization through word selection. Introducing auto-spaces might create issues when users want to include punctuation, and having two different methods for the same function could confuse people. We're trying to keep things simple.

**Comment by dean-futo** [comment]
@Annihilaton thanks for your request, but this could become messy because we already have a method for capitalization through word selection. Introducing auto-spaces might create issues when users want to include punctuation.
