### ISSUE TITLE
Display Long-Press Characters on Keys

### ISSUE THREAD

**Issue by Ambiguitytoday** [futo-org/android-keyboard#570]
### Use Cases

This streamlines input of special characters and numbers by displaying them as a smaller character on the key. So it does not require memorization of what character is associated with which key or having to move to this special character menu.

### Proposal

Add the picture of the sub character which can be displayed on the keycap, comma when the key button is pressed, and it opens the pop-up sub menu for the key. This is a feature on G board which Good from a user input perspective.

**Comment by haldi4803** [comment]
This?
![Screenshot_20241005-065957](https://github.com/user-attachments/assets/234b76bc-a419-48fc-b227-9bb040b35090)

Or how do you want it different?

**Comment by Ambiguitytoday** [comment]
Yes, just like that!

**Comment by haldi4803** [comment]
That IS the nightly build.
You can activate this in settings.
So you can close your issue.

**Comment by AddisonSnyder** [comment]
Been using FUTO keyboard since it came out, and I recently got a new phone and installed the latest version (0.1.24.2) and am unable to recreate this layout style in the newer version. The old version (0.1.24.1-playstore) has the layout 'default' but the new version has 'QWERTY' and no 'default' option. Guess I'll install the old version, but this seems weird/unintentional.

**Comment by AddisonSnyder** [comment]
Nevermind, I found the option under Keyboard->Long-Press Keys->Show Hints
