### ISSUE TITLE
Keyboard Ignores Personal Dictionary and Censors Profanity

### ISSUE THREAD

**Issue by driftywinds** [futo-org/android-keyboard#584]
### What happened?

I speak a lot of romanised or transliterated Hindi (write the language using the English alphabet) and have added words that I frequently use in my personal dictionary. I also use a lot of english cuss words.

The keyboard fails to recognise the personal dictionary and whenever I type a romanised Hindi word that is part of my personal dictionary the keyboard still tries to autocorrect it to a normal english word. Moreover if I use words like fuck and shit the keyboard also tries to autocorrect them no matter how I try to deal with it.

### Keyboard Version

0.1.23.2

**Comment by abb128** [comment]
Regarding cuss words, go to Text Prediction > Blacklisted Suggestions and turn off the profanity filter. If you use a large personal dictionary, you may find it helpful to disable Transformer LM because it has a limited amount of personal dictionary words it can use

**Comment by driftywinds** [comment]
> Regarding cuss words, go to Text Prediction > Blacklisted Suggestions and turn off the profanity filter. If you use a large personal dictionary, you may find it helpful to disable Transformer LM because it has a limited amount of personal dictionary words it can use

Thank you!! I didn't realise Blacklisted Suggestions could be tapped. What features would I miss out on if I turned off Transformer LM? Like would I lose autocorrect for example?

**Comment by just-simon** [comment]
Thank you @abb128!
This has been baffling me

**Comment by machinaeZER0** [comment]
New to the project so apologies for butting in here, but would it make sense to turn off the profanity filter by default? To an outsider it confused me more that what I was typing wasn't registering, which felt like a bug. Obviously the toggle would still be available for those who want to enable it. Defer to the dev(s), of course!

**Comment by calebfaruki** [comment]
> > Regarding cuss words, go to Text Prediction > Blacklisted Suggestions and turn off the profanity filter. If you use a large personal dictionary, you may find it helpful to disable Transformer LM because it has a limited amount of personal dictionary words it can use
> 
> Thank you!! I didn't realise Blacklisted Suggestions could be tapped. What features would I miss out on if I turned off Transformer LM? Like would I lose autocorrect for example?

This should probably be better advertised. Almost everyone cusses.

**Comment by dalaeance** [comment]
It's crazy that basic words for the names of body parts, that even 5 year olds use, are counted as "offensive." 

This kind of default censorship feels like it belongs in a world that existed before the '90s.

I agree with:
1. Leaving the option there for those who want it, but
2. Setting it to off by default, because
3. It is so confusing when your keyboard is repeatedly not outputting common words. Also, 
4. Making it more obvious that "Word Blacklist" is tappable. Perhaps we should just intuitively know this, but the way it's correctly displayed kinda makes it look like a heading for the toggles beneath it. I reckon just adding a right-adjusted `›` could make it more obvious that there's more there.

Part of the problem may also be that "Word Blacklist" implies that that's where you go to add words you want blocked, not that there are toggles that are already turned on and blocking common words. If they're just exploring the settings on initial setup, it's likely that many people wouldn't tap on that because they don't yet know what they need to block. And, by the time they come across something they'd want to personally block, they may have forgotten about that option, because who frequents their keyboard settings?
