### ISSUE TITLE
Consolidated Meta-Issue: Swipe Typing Inaccuracy and Functionality Issues Across Languages and Complex Words

### ISSUE THREAD

**Issue by dean-futo** [futo-org/android-keyboard#665]
### What happened?

Swipe typing has several issues that make it unreliable, especially for longer or more complex words, multilingual settings, and fast typing. Users often face inconsistent word recognition, accidental activation of voice input, and frequent misrecognition of letters, which results in incorrect suggestions or no output at all. These problems affect various languages, including Spanish and Finnish, and are also evident in context-sensitive swiping, where the keyboard fails to accurately predict based on the surrounding text. Moreover, difficulties arise when switching between regular typing and swipe typing, with delays leading to ghosted or missed letters. Users have also noted that the performance of swipe typing tends to decline over time, further reducing the feature's reliability.

Consolidated Tickets:
- #131: Rapid swipe typing leads to missed or incorrect words, as the algorithm struggles to recognize short, common terms.
- #165: The current sensitivity for swipe gestures is too rigid, causing inaccurate swipes and a subpar user experience when switching from other keyboards.
- #185: Swipe typing fails to leverage context for better word predictions, resulting in nonsensical outputs, particularly in sentence-based entries.
- #206: Turning off word suggestions also disables swipe typing completely, preventing users from utilizing the swipe feature.
- #332: The performance of swipe typing deteriorates over time, becoming less accurate and ultimately unusable without a reinstall.
- #363: Users with larger fingers or quick-moving thumbs face challenges with inaccurate swipe recognition, and double letters are often detected inconsistently.
- #408: The accuracy of swipe typing in Spanish is significantly low, missing 30-50% of words even when swiped correctly.
- #427: Users experience delays when transitioning from normal typing to swipe typing, often missing the first few letters of the swipe.
- #512: Occasionally, swipe typing unintentionally activates voice input, interrupting the typing flow.
- #530: Swipe typing often produces incorrect and confusing results, sometimes suggesting acronyms or obscure terms instead of common words.
- #560: Swipe typing struggles with complex or lengthy words, often resulting in no response or incorrect suggestions.
- #661: In Finnish, swipe typing misidentifies common words like "Minä" while correctly suggesting similar-looking alternatives.

There are a handful of problems with swipe typing that compromise its accuracy and reliability in various situations. For longer, more complex, or multilingual words, the keyboard often fails to recognize the swipe or provides incorrect suggestions. Sometimes, the swipe gesture unintentionally activates voice input. This problem is made worse by poor sensitivity and delays when switching between regular typing and swiping, which can lead to missed letters or ghosted input. Over time, the effectiveness of swipe typing diminishes, making it almost unusable for some users. Furthermore, users have noted that turning off word suggestions completely disables swipe typing, and the absence of context-sensitive predictions results in nonsensical word suggestions.

Proposed Fixes:
- Enhance the swipe typing algorithm to better manage long and complex words, ensuring that swipes are recognized accurately and consistently.
- Introduce context-sensitive predictions that consider the surrounding text while swiping, which will boost the accuracy of suggestions.
- Modify swipe sensitivity settings to cater to various typing speeds and finger sizes, enabling users to adjust the responsiveness of the swipe feature to their preference.
- Eliminate the lag between normal typing and swipe typing, ensuring that swipes are detected immediately upon switching input modes.
- Tackle the issue of swipe typing performance declining over time by enhancing the stability and reliability of the feature.
- Make sure that turning off word suggestions does not completely disable swipe typing, allowing users to swipe without predictive text if they choose.
- Resolve the problem of voice input being triggered accidentally during swipe typing to prevent unintentional activation.
- Concentrate on enhancing multilingual support, especially for languages like Spanish and Finnish, where swipe typing currently overlooks a considerable number of words.

### Keyboard Version

Various

**Comment by jedinjapan** [comment]
For users seeking to assist in this, there is an ongoing dataset collection effort at https://swipe.futo.org/ to improve this functionality. I did not see this mentioned some of the other issues I looked at, but just in case adding it to the Meta-issue here for visibility: if this issue is affecting you, contribute to the dataset on the website.

**Comment by dean-futo** [comment]
I further consolidated this meta-issue into more specific segments, so closing this one. Breakdown:
- #165 is now merged with #363
- #661 and #408 are now merged with #560

The others are standalone. Please provide any further input on those specific segmented issues.

**Comment by zanfur** [comment]
The de facto standard "best" swipe typing experience was Swype, and this is not an uncommon opinion.  There are three *major* things it had that improved input speed and accuracy, that basically nothing has had since:

* Moving the swipe trail above the keyboard would capitalize the most recent letter
* The "hidden"/punctuation characters on the swiped keys would be considered (allowing things like email addresses to be swiped, as well as various emojis)
* "Looping" the swipe trail on a key would cause it to be doubled (allowing for e.g. "to" vs "too" or "desert" vs "dessert" to be very consistent)

I bring up the specific 3 points above, because those are ones that I can't assist by on your swipe dataset gathering page, because they're simply not covered by the featureset of FUTO swipe input. There were other very nice features as well, such as being able to swipe "a" and "I" instead of needing to tap them, but the key reason it is so beloved by so many is that focused on input speed above all else.  I love FUTO and what it stands for, and I'm a paid user, but the swiping is sometimes so slow and cumbersome that I switch to Google Keyboard when I'm in a rush, simply because it's just that much faster to input.  I would love for that to no longer be a consideration I need to weigh against my own privacy.

Related, I would love a feature to explicitly opt in to giving the dataset of my own swiping.  I believe you will get a much much more representative sample of "real use" if FUTO Keyboard is able to save this data for later export and upload.
