### ISSUE TITLE
Consolidated Meta-Issue: Autocorrect Inaccuracies and Inconsistent Behavior in Specific Contexts

### ISSUE THREAD

**Issue by dean-futo** [futo-org/android-keyboard#666]
### What happened?

The autocorrect feature has many problems that can frustrate users. It struggles with valid words, slang, and text close to the spacebar or number line. Additionally, it applies corrections inconsistently in some text fields, doesn't recognize or correct alphanumeric words, and often replaces correct words with irrelevant suggestions. These issues make the keyboard less dependable, particularly for users who frequently use slang or work in text fields where autocorrect and prediction may completely fail.

Consolidated Tickets:
- #522: Autocorrect mistakenly changes valid words to incorrect alternatives, even when the original word is correct (e.g., changing "switch" to "stretch").
- #502: The autocorrect and prediction features occasionally stop functioning in certain text fields, rendering the keyboard unusable until a manual reset is performed.
- #464: Common slang terms like "u" and "ur" are incorrectly substituted with formal words such as "I" and "it."
- #452: Autocorrect does not work in specific applications like Discord and in the search bars of browsers like Edge, Google, and Brave.
- #372: Autocorrect has difficulty recognizing words typed incorrectly due to mistypes from the 'xcvbn' key row, especially near the spacebar.
- #344: The autocorrect feature fails to operate when the spacebar is pressed in the address bars of certain browsers.
- #300: The word "knob" is replaced by "innovation" or other incorrect terms, likely due to the offensive word filter.
- #271: Mistyped characters that are close to the spacebar (e.g., hitting 'b' instead of the spacebar) are not corrected by autocorrect.
- #268: Autocorrect does not correct common words when they are mistyped with alphanumeric characters (e.g., "b3n" instead of "ben").

Autocorrect is acting inconsistently in different text input situations. Users have noticed that valid words are sometimes replaced incorrectly, while common slang or informal terms get changed to more formal alternatives, complicating casual texting. The keyboard often doesn't apply autocorrect in certain text fields, like search bars or message boxes in specific apps, which means users have to edit their text manually. Additionally, when typing near the spacebar or number row, autocorrect fails to catch typical mistakes, such as pressing 'b' instead of the space. It also has trouble with alphanumeric inputs, not correcting words like "b3n" to "ben." In some instances, the offensive word filter mistakenly flags innocent words like "knob," replacing them with unrelated suggestions such as "innovation."

Proposed Fixes:
- Enhance the autocorrect feature to avoid changing valid words, ensuring that correct inputs remain unchanged.
- Incorporate support for popular slang and informal texting abbreviations (e.g., "u," "ur"), allowing them to be accepted without alteration.
- Resolve the problem where autocorrect and prediction features become inactive in certain text fields, ensuring they work consistently across all applications and input areas.
- Improve the precision of autocorrect when addressing typos made near the spacebar or number row, especially when characters from the 'xcvbn' row are mistakenly pressed.
- Fix the issue where autocorrect struggles with alphanumeric entries, enabling it to recognize and correct terms like "b3n" to "ben."
- Examine the offensive word filter to ensure it does not mistakenly replace benign words with unrelated suggestions, such as changing "knob" to "innovation."
- Enable users to personalize autocorrect settings for specific text fields, such as allowing toggling of autocorrect in address bars or search fields where URL input is frequent.

### Keyboard Version

Various

**Comment by supermarble94** [comment]
it also really likes to capitalize words at the start of sentences via autocorrect even when I have "auto-capitalization" disabled

**Comment by BurntVoxel** [comment]
I have a weird idea related to the bugs involving slang: what if you tried implementing a "formality" setting? 
Instead of just filtering out offensive words, what if you allowed toggling individual rules for autocorrect, and also had a slider with presets that range from "chill" to "grammar nazi"?

At strict end, disallow slang, potentially offensive words Personally, I would prefer that "u" is replaced with "I", and "~~ur~~, it", even though I know that many people don't want that correction. So maybe just make that rule optional? On top of the though, maybe leave the config open to allow toggling any future flexibility features. Such as, I don't know if word lists support "mixing" words by adding suffixes to fill out the dictionary, but if that ever does get added, maybe disable that for strict mode.

At the relaxed end, allow slang and potentially offensive terms. But also relax other rules. Is there a grammar checker engine? If so, disable that here, permit intentionally bad grammar here, like "Whiskers forgot how to cat for a minute there".

If this does get implemented, it would be even better if that could be configured per application, but I imagine that would be much more complicated.

**Comment by derekhansell** [comment]
Very happy to see y'all tackling this head on. I've resisted switching back to Swiftkey for now, but it's extremely cumbersome to proofread every thing I type. But your speech-to-text continues to be TOP NOTCH! It's the main reason I haven't switched back yet, other than, ya know, the whole privacy thing.
