### ISSUE TITLE
Option to turn off emoji/emotes key next to space

### ISSUE THREAD

**Issue by krwow** [futo-org/android-keyboard#702]
### Use Cases

I don't use emoji key and would like to have longer space bar as it can be achieved in other keyboard apps.

### Proposal

Just adding extra switch to turn off emoji key and make a spacebar key longer in a result.

**Comment by a-s-h-h-h** [comment]
Hi there! 

You already can do this! Though it is a bit more complicated than a simple switch.

open the keyboard's Settings (just hold the comma left of the space bar)

> keyboard and typing > edit actions 

remove the "emojis" button from the "action key" section. Do this by touching and holding, then just dragging it elsewhere.  Leave this section empty to get rid of the button completely. If you put something else there it will just replace the emoji key rather than get rid of it.

Hope this helps!

       ~ _ashhh_

**Comment by krwow** [comment]
That's hidden too much...

But thanks! I'll close it as there's already solution for that, just maybe not too clear.

**Comment by lallinger** [comment]
> Hi there!
> 
> You already can do this! Though it is a bit more complicated than a simple switch.
> 
> open the keyboard's Settings (just hold the comma left of the space bar)
> 
> > keyboard and typing > edit actions
> 
> remove the "emojis" button from the "action key" section. Do this by touching and holding, then just dragging it elsewhere. Leave this section empty to get rid of the button completely. If you put something else there it will just replace the emoji key rather than get rid of it.
> 
> Hope this helps!
> 
> ~ _ashhh_

Slight note: you need to force restart futo keyboard for this to take effect
