### ISSUE TITLE
Add Keyboard to F-Droid Store

### ISSUE THREAD

**Issue by DoS007** [futo-org/android-keyboard#720]
### Use Cases

Someone wants to install the keyboard from f-droid, see fdroid store: https://f-droid.org/de/

It's probably the most popular opensource app store.

**Comment by MXC48** [comment]
> ### Use Cases
> 
> Someone wants to install the keyboard from f-droid, see fdroid store: https://f-droid.org/de/
> 
> It's probably the most popular opensource app store.
> 
> ### Proposal
> 
> _No response_
> 
> ### References
> 
> _No response_

Futo has a official repo for the F-Droid client

**Comment by DoS007** [comment]
@MXC48 When i search for "futo keyboard" I don't see it on f-droid store?

**Comment by MXC48** [comment]
Add this repo to your F-Droid client 
https://app.futo.org/fdroid/repo?fingerprint=39D47869D29CBFCE4691D9F7E6946A7B6D7E6FF4883497E6E675744ECDFA6D6D

**Comment by DoS007** [comment]
@MXC48 Why isn't it available when searching just normal on f-droid? Other apps are also directly available on f-droid.

**Comment by MXC48** [comment]
Because the developers just didn't put it in F-droid for different reasons, you can go ask them on discord on you want but it seems to me that it's because the release times on the platform are too long compared to what they need at the moment 
We must not forget that the application is in alpha and that everything can change in the future

**Comment by DoS007** [comment]
@MXC48 Ok, i wait then until it's officially in f-droid store.
